// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPI_Apollo.Infraestrutura;

#nullable disable

namespace WebAPI_Apollo.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240605224925_InitialFirstMigration")]
    partial class InitialFirstMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.5");

            modelBuilder.Entity("WebAPI_Apollo.Domain.Model.Estatisticas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("AguaDiaria")
                        .HasColumnType("REAL");

                    b.Property<double>("IMC")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Estatisticas");
                });

            modelBuilder.Entity("WebAPI_Apollo.Domain.Model.InformHome", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("TEXT");

                    b.Property<int>("NumAmigos")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumMensagensNaoLidas")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumNotificacoesNaoLidas")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumSolicitacoesAmizade")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("InformHome");
                });

            modelBuilder.Entity("WebAPI_Apollo.Domain.Model.Interacoes.Amizade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("Destinatario")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Remetente")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Amizades");
                });

            modelBuilder.Entity("WebAPI_Apollo.Domain.Model.Interacoes.Curtida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("Destinatario")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Remetente")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Curtidas");
                });

            modelBuilder.Entity("WebAPI_Apollo.Domain.Model.Interacoes.Mensagem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Destinatario")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Remetente")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Mensagens");
                });

            modelBuilder.Entity("WebAPI_Apollo.Domain.Model.Interacoes.Notificacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("Destinatario")
                        .HasColumnType("TEXT");

                    b.Property<string>("MensagemDaNotificacao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Remetente")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("TEXT");

                    b.Property<int>("TipoDeNotificacao")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Notificacoes");
                });

            modelBuilder.Entity("WebAPI_Apollo.Domain.Model.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagemBase64")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NumComentarios")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumCurtidas")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("WebAPI_Apollo.Domain.Model.TestTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CriadaEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TestTable");
                });

            modelBuilder.Entity("WebAPI_Apollo.Domain.Model.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<float>("Altura")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Esporte")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("IdEstatisticas")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Idade")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImagemPerfil")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PalavraRecuperacao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("Peso")
                        .HasColumnType("REAL");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("XP")
                        .HasColumnType("INTEGER");

                    b.Property<int>("XP_ProximoNivel")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
